
# Generated by Django 3.2.5 on 2021-07-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(

            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('health', 'health'), ('entertainment', 'entertainment'), ('utilities', 'utilities'), ('work', 'work'), ('insurance', 'insurance'), ('other', 'other')], default='entertainment', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(max_length=30)),
                ('subscription_cost', models.CharField(max_length=50)),
                ('subscription_start', models.DateTimeField()),
                ('subscription_frequency', models.CharField(choices=[('M', 'monthly'), ('Y', 'yearly')], default='M', max_length=1)),
                ('subscription_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.category')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('transaction_cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('transaction_subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.subscription')),
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
