# Generated by Django 3.2.5 on 2021-07-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20210713_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_category',
        ),
    ]
