# Generated by Django 3.2.5 on 2021-07-14 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0003_remove_subscription_subscription_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
